apiVersion: v1
kind: ConfigMap
metadata:
  name: search-platform-api-config
  labels:
    app.kubernetes.io/name: search-platform-api
    app.kubernetes.io/component: api
  annotations:
    reloader.stakater.com/match: "true"
data:
  NODE_ENV: production
  HOST: 0.0.0.0
  PORT: "3000"
  LOG_LEVEL: info
  OPENSEARCH_BOOTSTRAP_ENABLED: "false"
  OTEL_ENABLED: "true"
  OTEL_METRICS_PORT: "9464"
  OTEL_METRICS_ENDPOINT: /metrics
