apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: search-platform-api
  labels:
    app.kubernetes.io/name: search-platform-api
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: search-platform-api
