version: '3.9'

services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch-local
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9600:9600'
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres-local
    environment:
      POSTGRES_DB: search_service
      POSTGRES_USER: search_user
      POSTGRES_PASSWORD: search_password
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U search_user -d search_service"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:3000/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
