apiVersion: v1
kind: ConfigMap
metadata:
  name: search-platform-api-config
  labels:
    environment: production
data:
  NODE_ENV: production
  LOG_LEVEL: info
  OTEL_ENABLED: "true"
  OPENSEARCH_BOOTSTRAP_ENABLED: "false"
