name: CI

on:
  pull_request:
  push:
    branches:
      - "**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20"

jobs:
  quality:
    name: Run quality gates
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint, typecheck, and test
        run: npm run ci

      - name: Run vulnerability audit
        id: npm_audit
        run: npm audit --omit=dev --json | tee npm-audit.json

      - name: Upload npm audit report on failure
        if: failure() && steps.npm_audit.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: npm-audit.json

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.22.0
        with:
          scan-type: "fs"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          format: "table"
          exit-code: "1"

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: quality
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}-

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: search-platform-api:ci
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Scan built image with Trivy
        uses: aquasecurity/trivy-action@0.22.0
        with:
          image-ref: search-platform-api:ci
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          format: "table"
          exit-code: "1"
